name: BP Design
favicon: null
layout_spectrum: 0.91623
typography_spectrum: 0.14606
title: BP Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a6c8e9'
    - '#6ca1e4'
    - '#716765'
    - '#202022'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
